// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using EvolutionaryArchitecture.Fitnet.Passes.Data.Database;

#nullable disable

namespace EvolutionaryArchitecture.Fitnet.Migrations;

[DbContext(typeof(PassesPersistence))]
[ExcludeFromCodeCoverage]
partial class PassesPersistenceModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("Passes")
            .HasAnnotation("ProductVersion", "7.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("EvolutionaryArchitecture.Fitnet.Passes.Data.Pass", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<Guid>("CustomerId")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset>("From")
                .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset>("To")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.ToTable("Passes", "Passes");
        });

        modelBuilder.Entity("EvolutionaryArchitecture.Fitnet.Passes.Data.Database.OutboxMessage", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<Guid>("CorrelationId")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Payload")
                .IsRequired()
                .HasColumnType("text");

            b.Property<DateTimeOffset?>("ProcessedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Type")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.HasKey("Id");

            b.HasIndex("ProcessedAt");

            b.HasIndex("Type", "CorrelationId")
                .IsUnique();

            b.ToTable("OutboxMessages", "Passes");
        });

        modelBuilder.Entity("EvolutionaryArchitecture.Fitnet.Passes.Data.Database.PassesSagaState", b =>
        {
            b.Property<Guid>("SagaId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<Guid>("CorrelationId")
                .HasColumnType("uuid");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("SagaType")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("character varying(200)");

            b.Property<int>("Status")
                .HasColumnType("integer");

            b.Property<DateTimeOffset>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("SagaId");

            b.HasIndex("SagaType", "CorrelationId")
                .IsUnique();

            b.ToTable("SagaStates", "Passes");
        });
#pragma warning restore 612, 618
    }
}